### ISSUE TITLE
Get the place and date of publication for the record

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#174]
Use the new endpoint in dor-services-app.  Use this to set the access when depositing to SDR.  

Question: What should we do if the catalog record does not have this information?
Options: 
 - [x] Use the most restrictive rights
~~- [ ] Get a person involved (need detail)~~

~~Question: Do we want to store this metadata in the database? If a person gets involved we might need a place to store it?~~

No need for now.  If algorithm doesn't work, assume copyrighted (citation only).

**Comment by justinlittman** [comment]
Here's my thought on how to approach this:
* Replace fetching the catkey at the beginning of the workflow with fetching the MARCXML.
* Store the MARCXML instead of the catkey.
* Parse the catkey, date, and place when needed from the MARCXML.

This approach is based on the assumption that the following are likely to evolve over time:
* How/where the dates and places of publication are parsed from the MARCXML.
* The algorithm for determining if a book is in copyright.
Thus, it will be helpful to have the MARCXML stored and to do that work late (rather, for example, then parsing out and storing and/or making a copyright determination in mass in advance).

Now, suppose we receive the directive to accession the out of copyright books first. Assuming that we have implemented a simple priority column for prioritization, then we could write a little task that went through the waiting books and set priority based on a copyright determination.

**Comment by mjgiarlo** [comment]
@justinlittman makes a convincing case for stuffing the MARCXML, as much as it pains me to admit. :smile:
