### ISSUE TITLE
Determine if source book data reliably records RTL/LTR orientation

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/google-books#184]
Review Google Book data to determine how we might distinguish between LTR and RTL books, which will inform which process tag to assert with books as they are processed.

**Comment by ndushay** [comment]
Ask cataloging if we can tell from our data?   Maybe the language in 008?

**Comment by andrewjbtw** [comment]
This is included in all 36 METS files we have in the sample of downloaded books from last year. By that standard, I think we can expect it to be included with the vast majority of books.

The element is:

```xml
<gbs:readingOrder>left-to-right</gbs:readingOrder>
```
There's only one catch: the language detection is sometimes faulty. Barcode 20500032670 in the sample is listed as right-to-left but that is clearly wrong when you look at the pages. The book is actually left-to-right and the language detection algorithm was probably thrown off by the many pages of data/numbers. It's probably still more accurate than if we tried to do the detection ourselves.

**Comment by mjgiarlo** [comment]
@andrewjbtw :speech_balloon: 
> This is included in all 36 METS files we have in the sample of downloaded books from last year. By that standard, I think we can expect it to be included with the vast majority of books.
> 
> The element is:
> 
> ```
> <gbs:readingOrder>left-to-right</gbs:readingOrder>
> ```

Question: what possible values should we anticipate in this element? Just `left-to-right` and `right-to-left` or are there other values? If there are other values, or if it's empty or missing, should we just default to LTR?

Good find! Thanks, Andrew.

**Comment by andrewjbtw** [comment]
I have so far not been able to find a specification or controlled vocabulary for that field in the Google documentation. 

I think that:

1. If there's nothing in the field, or the field isn't even present, we should default to LTR
2. It's probably safe to assume that LTR and RTL are the only values, but if it's not too much trouble we could log it if there's a value that's not one of those two so that someone could come back to it and see what's going on. I think it would be very needle-in-haystacky to look for a value that's not one of those two without an idea of what that value would be.
