### ISSUE TITLE
Scrutinize deposited book to determine if valid/correct

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/google-books#296]
This issue is for @andrewjbtw to help us figure out if books flowing through this app into SDR "look right." 

There will be books in three buckets for which we need to fetch barcodes, prioritize for retrieval and then review

- [ ] out of copyright (world discover and read, images shelved)
- [ ] in copyright, but out within 5 years (world discover, no read, embargoed to world read, images shelved)
- [ ] in copyright, more than 5 years until out (world discover, no read, embargoed to world read, no images shelved)

**Comment by justinlittman** [comment]
https://argo-stage.stanford.edu/view/druid:hc140jr8573 can be reviewed (and any book deposited after it).

**Comment by andrewjbtw** [comment]
Content metadata looks correct to me. But in looking at this, I realized I may have been misunderstanding the relationship between rights and the publish/shelve/preserve settings. I'm checking on that with Ben.

I thought for "dark" content, publish/shelve are both "no". But I see examples in production where those are set to "yes" for content where rights are "dark". I think what we have makes sense, so I don't think what we are doing is wrong. But I want to make sure I understand why production looks that way and whether there's any reason to change what we've done for Google Books.

**Comment by andrewjbtw** [comment]
Looking at the most recent books (based on "deposit succeeded" in the app), there are a number of problems with deposited items. This comment is only about contentMetadata. I'll make a separate comment for rightsMetadata.

For example, I looked at 

https://argo-stage.stanford.edu/view/druid:bq739dt2283 (in copyright)
https://argo-stage.stanford.edu/view/druid:dh840tn6627 (public domain)

1. No collection is being assigned. Books should be assigned to a collection as well as an APO. For stage, the collection is: https://argo-stage.stanford.edu/view/druid:ks963md4872 

Ticket: https://github.com/sul-dlss/google-books/issues/391

2. The page resources should be labeled "Page" not "Object". See this book deposited during the analysis workcycle last year for an example of how this should work: https://argo.stanford.edu/view/druid:ph649dt5778

Ticket: https://github.com/sul-dlss/google-books/issues/392

3. The XML file and the checksum file are being treated as pages. They should be considered their own objects.

Ticket: https://github.com/sul-dlss/google-books/issues/393

4. For public domain books, the checksum.md5 file should be preserve only. Currently, we are marking it as publish and preserve.

Ticket: https://github.com/sul-dlss/google-books/issues/394

**Comment by andrewjbtw** [comment]
For rightsMetadata, it looks like the top-level rights are all correct in terms of discover and read ("world" vs. "none").

For the statements, I realize we're still waiting on the official wording. We are currently including empty tags/attributes for Creative Commons and Open Data Commons licensing that is probably part of the full rightsMetadata template:
```xml
   <human type="creativeCommons"/>
    <machine type="creativeCommons" uri=""/>
    <human type="openDataCommons"/>
    <machine type="openDataCommons" uri=""/>
```
 I don't think it's necessarily a problem to include these as empty tags because they don't appear to send anything to the purl, but I also don't think it's strictly necessary. I believe we can include just the statements we actually use.

**Comment by andrewjbtw** [comment]
For embargoMetadata and related settings:

1. The embargoMetadata datastream itself

The top-level rights are correct, as they're just going to public domain when that finally happens. 

But I think that the embargoMetadata needs to have its own rights statements as well, so that this will get substituted in when the rights are updated. Currently, there are no use or copyright statements in our embargoMetadata datastreams. 

Again, as with rightsMetadata, I realize that we are waiting on input for the actual statements, so I don't know if these are not included at the moment simply because we don't have those statements yet. The statements here should be the same ones that we are using for public domain books.

Ticket https://github.com/sul-dlss/google-books/issues/398

2. Including the embargo date in the rightsMetadata

The embargoMetadata documentation on Consul says that the release date is supposed to be in the rightsMetadata datastream:

> While under embargo, rightsMetadata will hold a copy of the embargo release date so that it is published in PURL and made accessible for online messages (e.g., "This item will be available on..."):
https://consul.stanford.edu/display/chimera/Embargo+management+--+the+embargoMetadata+datastream

If that is still accurate, we need to insert the release date into the rightsMetadata datastream as well.

Ticket https://github.com/sul-dlss/google-books/issues/399

3. publish/shelve settings for items in the five-year window

Items in the five year window need to have both publish and shelve set to yes for the page files and the XML file. Currently, they are only having shelve set. Without the publish setting, they won't become visible even after the rights change to world.

Ticket https://github.com/sul-dlss/google-books/issues/400

**Comment by andrewjbtw** [comment]
I think that's all the scrutiny I can do from the Argo view. I also want to look at the purl/stacks side of things, once the rebuild and reconfiguration of that environment is complete.

**Comment by peetucket** [comment]
Reconfirm google books objects match the new style (all books are citation only, nothing shelved)

**Comment by andrewjbtw** [comment]
In the time since the last scrutiny, policy changed to the following:

1. All files are preserve only, regardless of copyright determination.
2. All purls are citation-only (but with no files shelved because of point 1 above).
3. No embargoes or automatic publishes.

Under the new policy:

1. Rmbargo-related settings are gone so don't need reevaluation.
2. All rights are now discover=world, read=none.
3. Content metadata labels are correctly assigning page vs. object
4. Tags are correct.

The one thing that I see missing is the assignment of books to a collection. This happened for a while but seems to have stopped on 3/17. I've reopened https://github.com/sul-dlss/google-books/issues/391 for this.

**Comment by andrewjbtw** [comment]
I don't think there's anything left to scrutinize, so I'm going to close this.
