### ISSUE TITLE
Decide on what to do with serials that have different start publication dates

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#305]
From https://github.com/sul-dlss/google-books/issues/103#issuecomment-587243174 (Vitus Tang)

#### Problems with Date picked for serial publications. 

> In HathiTrust's Automated Bibliographic Rights Determination<https://www.hathitrust.org/bib_rights_determination> they have a special rule for serials:
>
>BibFmt eq 'SE' and VolDate exists:
>date_used = VolDate
>
>and VolDate is defined as " Latest year parsed from z30_description field. Set to null if nothing could be parsed or if no z30_description." 
>
>Don't know what their z30_description field is. 
>
>The problem with serial publications is that their publication date is a range of years, and that range can cross the "public domain"/"in copyright" boundary. Here's an example. Ckey 2019108 has Date1 = 1880 and Date2 = 1957. DateType is "d". Our rule says if Date2 > Date1, picks Date 2. In this case the date picked would be 1957, which is in copyright. But we actually have volumes that are designated as 1893, 1895, 1899, 1911-1924. Are these volumes in the public domain?
>
>Here is another example, the opposite of the one above. Ckey 348973 has Date1 = 1840, Date2 = 9999, DateType = c. According to our rules, 9999 = nil so the date picked would be 1840, which is in the public domain, but we have volumes that go all the way up to 1976. If we designate this entire serial as "public domain", would we be exposing some content that is still in copyright?

**Comment by jcoyne** [comment]
@peetucket I'm not really sure what to do with this.  Is there something actionable here?

**Comment by ndushay** [comment]
So in a perfect world, we want to know the copyright date for each barcode in a bib record (with a ckey -- each barcode for a ckey).   This is especially tricky for serials, as Vitus notes.  Not just for the publication date, that he mentioned but also because there can be multiple serial issues per bound library volume, and the barcode is associated with a bound volume, I'm pretty certain.

Action Item:  check that the barcode is associated with the bound volume
Action item:  check that the copyright date goes with the serial issue
Action item:  check that we have multiple serial issues in a single bound volume.

Now for some info.  Totally ugly, but hopefully useful:

the Marc record that SearchWorks indexes is *different* from the plain bib record from Symphony.  The process to index MaRC data for SearchWorks actually starts with pre-processing our MaRC bib data.  There are 2 relevant things added before SearchWorks indexes marc:
-  the MHLD information for serials (at least it used to be added -- I'm not seeing it and this practice may have been abandoned.  Ask access team;  if it is still happening, ask for an example ckey)
- adds information from the item records in Symphony to the bib record as 999 fields

You can see the Marc that is index into Solr for SearchWorks by asking for marcxml to be returned from Solr, e.g.

https://sul-solr-a.stanford.edu/solr/searchworks-prod/select?q=2019108&fl=id,marcxml,item_display&facet=false&wt=xml

In any case, there can be serial date information in the call number, which is in the item_display field (but oy, call numbers -- you would need to ask Vitus if you could reliably look there ... I doubt it).

Here is an item_display field value from https://sul-solr-a.stanford.edu/solr/searchworks-prod/select?q=2019108&fl=id,marcxml,item_display&facet=false

 "36105015593911 -\|- SAL3 -\|- STACKS -\|-  -\|- STKS-PERI -\|- 977.6 .M66R ... -\|- dewey 977.60000000 m66r ... -\|- ml3l1~qss}tzzzzzzz~dtt8~}}}~~~~~~~~~~~~~~~~~~~~~~~ -\|- 977.6 .M66R **1893** -\|- dewey 977.60000000 m66r zzyrqw~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -\|-  -\|- DEWEY"
-- | --

note it has a Dewey call number;  the vast majority of stanford holdings are LC call numbers.  :-P

Here is an item display field from 348973 (https://sul-solr-a.stanford.edu/solr/searchworks-prod/select?q=348973&fl=id,marcxml,item_display&facet=false)

"36105007447761 -|- GREEN -|- STACKS -|-  -|- STKS-PERI -|- HT851 .A7 ... -|- lc ht  0851.000000 a0.700000 ... -|- en~i6~~zruy}zzzzzz~pz}szzzzz~}}}~~~~~~~~~~~~~~~~~~ -|- HT851 .A7 SER.6:V.8:NO.1,3-4-V.12:NO.3 1 -|- lc ht  0851.000000 a0.700000 7l8}zzzzzt~4}zzzzzr~cb}zzzzzy~zzzzzw~zzzzzv~4}zzzzyx~cb}zzzzzw~zzzzzy -|-  -|- LC"

Note LC call number and it has volume info, but not year info.  However, some other item_display fields from that record DO have the year info in the call number:

"6105007392751 -|- GREEN -|- STACKS -|- -|- STKS-PERI -|- HT851 .A7 ... -|- lc ht 0851.000000 a0.700000 ... -|- en~i6~~zruy}zzzzzz~pz}szzzzz~}}}~~~~~~~~~~~~~~~~~~ -|- HT851 .A7 SER.3:V.20-22 **1876-1880** -|- lc ht 0851.000000 a0.700000 7l8}zzzzzw~4}zzzzxz~zzzzxx~zzyrst~zzyrrz~~~~~~~~~~ -|- -|- LC"

**Comment by ndushay** [comment]
Here's what the access team says.   So there may be granular info available in the marcxml in SearchWorks Solr:

![image](https://user-images.githubusercontent.com/96775/75725379-36f30480-5c95-11ea-90db-07a10e6e55a4.png)

**Comment by peetucket** [comment]
Changes to algorithm in #379
