### ISSUE TITLE
Get list of barcodes for researcher use cases for prioritization of download

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/google-books#327]
As a researcher in the Law school, I might want to define a corpus for that we want to prioritize highly.

Example criteria:
Language: English
Date: Post 1965
Topic: Law
Type: Book

In searchworks this would look like this (but it doesn't give us barcodes):

https://searchworks.stanford.edu/?f%5Baccess_facet%5D%5B%5D=At+the+Library&f%5Bformat_main_ssim%5D%5B%5D=Book&f%5Blanguage%5D%5B%5D=English&f%5Btopic_facet%5D%5B%5D=Law&range%5Bpub_year_tisim%5D%5Bbegin%5D=1965&range%5Bpub_year_tisim%5D%5Bend%5D=2023&search_field=dummy_range

**Comment by justinlittman** [comment]
Run a search where? And is that prioritize for processing?

**Comment by jcoyne** [comment]
@justinlittman offline, some sort of on time tool.  Perhaps this can be done in Symphony?

**Comment by ndushay** [comment]
https://sul-solr-a.stanford.edu/solr/searchworks-prod/select?q=interesting&pub_year_tisim[2000:2020]&fl=id,barcode_search&wt=csv

`fl` gets you whatever fields you ask for;  we want barcode_search for barcodes, and id is the ckey which can be very helpful.

`wt` is the response format:  json by default, can be csv or xml or whatever.

`q` is the actual query

`pub_year_tisim[2000:2020]` should be searching the range of the publication year, as defined by searchworks indexing ...

https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html

I'm happy to help with refinements.

**Comment by ndushay** [comment]
the query can be more complex;  I can come up with a query against any facet or any field on the advanced search form, or whatever ...

**Comment by cncoleman** [comment]
I took a look at @jcoyne 's query above. We definitely want something more broad than that. When I looked at the Topics facet in Searchworks it seemed like a very long list and was not presented in a hierarchical way so it was difficult to see what my selection was excluding. So I spoke to Vitus about it. He said he could make the selection in Symphony, get the barcodes, check those against what was sent to Google. One reason that appeals to me is that if it turns out that none of Crown's holdings went to Google, we may end up with a much shorter list. Not useful to RegLab. We want to err on the side of throwing a wider net.

@ndushay can you achieve the same thing that Vitus suggested? 

The parameters would be:
1. LSCH LAW as well as any high-level SH with a sub-category of law and legislation
2. Any resource type (not just books)
3. Post 1965 + "unknown" or unspecified dates
4. English language + language unspecified.

If it makes more sense to get this from Vitus, let me know. He said it could take a week or a few days.

**Comment by peetucket** [comment]
I think if Vitus is willing and able to get a list of barcodes that match your request, that is a great solution and enable us to both service this need and confirm our code works.  If this is a path forward for any future requests as well, that would be great.

**Comment by cncoleman** [comment]
OK. I'll send the request on to Vitus.

**Comment by peetucket** [comment]
Thanks!

**Comment by peetucket** [comment]
From Mark Algee-Hewitt (Law) to Tom on March 3:

```
Ideally, we would be interested in recovering the books that fall under the P designation in the LC first, particularly: P, PN, PQ, PR, and PS. We are specifically interested in recovering the novels held in PN, PQ, and PR, but also the literary critical books held in the other call numbers.
```

**Comment by peetucket** [comment]
Law barcodes: https://drive.google.com/open?id=1WpEsfk5DfZkgSG9rbXqnCGKlPwjBMdzH
English barcodes: https://drive.google.com/open?id=1HHRHJxy16rftlXJ43GoACIdTPrySXOTZ
