### ISSUE TITLE
Change algorithm for determing copyright status for serials

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/google-books#379]
Based on work in #103, we have chosen to be conservative about serial dates.

So we need changes in https://github.com/sul-dlss/google-books/blob/master/app/models/marc_xml_record.rb 

Implement an initital check to decide if the barcode represents a serial, by looking at the code in Leader/07 == 's', e.g.
<marc:leader>01484cas a2200361 a 4500</marc:leader>

A. If we determine we have a serial, then:

1. For a date code of "c" (as computed in this method https://github.com/sul-dlss/google-books/blob/master/app/models/marc_xml_record.rb#L87-L89),  set the `determined_date` as the current year.

2. For a date code of "d" or "t" or "u" as computed in that method above, use `date2` if it is present/not nil for `determined_date`, otherwise use the current year.

B. If serial code of 's' is not found Leader/07, keep the current logic.

Ref: a cheat sheet on marc codes: https://www.loc.gov/marc/bibliographic/bd008a.html

**Comment by peetucket** [comment]
Worked on this with help from @jgreben ... both of us can try and answer questions.

**Comment by peetucket** [comment]
@vitustang The goal of this ticket is to update our algorithm to be conservative when it comes to serials.  Since we are getting metadata at the level of a ckey and not a barcode, we are going to use dates from the ckey record even though this may result in some public domain barcodes being marked as in copyright.  Can you help us decide if our approach described above to modify the algorithm we currently have implemented in https://github.com/sul-dlss/google-books/blob/master/app/models/marc_xml_record.rb makes sense?

**Comment by vitustang** [comment]
@peetucket I agree with #1 and #2. Basically a conservative approach for serial would be to pick a date for copyright determination only from Date2. In other words Date1 can be ignored if the record is a serial (which can be determined by looking at the code in Leader/07. An "s" signifies serial) because you can never safely determine the copyright status based on the beginning date.

Serial records use only three "Date type": c, d, and u. "c" for currently published, "d" for ceased publication, and "u" for status unknown. Date2 would be 9999 if date type = c, and uuuu if date type = u. So both could be mapped to in copyright. Only when the serial has ceased publication (date type = d) and the Date2 date is before the threshold date (e.g. < 1925 for US publication) could it be safely considered to be in the public domain.

The situation described in #3 above (date type = t) should not happen. But if it does, the conservative approach would be to put it in the "in copyright" category, because you can't be sure what that Date2 is. Is it a copyright date, which is what the date type implies, or is it the ending date of the serial. You can't tell without looking at the rest of the record.

**Comment by peetucket** [comment]
Thanks @vitustang .  I adjusted the description of the logic in my ticket.  For my situation #3, I was trying to be conservative around the edge case (even though we would not expect it to happen)...again defaulting to assuming copyright instead of looking at the first year.  Maybe its not needed though.

Another question, is Leader/07 denoting a location of a field in the the MarcXML?

**Comment by vitustang** [comment]
@peetucket Yes, Leader/07 is the eighth byte of this field:

<marc:leader>01484cas a2200361 a 4500</marc:leader>

**Comment by justinlittman** [comment]
@peetucket If my understanding of our current code is correct, then what we need is to know is how to determine the embargo date. Whether something is in/out of copyright is determined by whether it has an embargo date.

**Comment by jgreben** [comment]
> Serial records use only three "Date type": c, d, and u. "c" for currently published, "d" for ceased publication, and "u" for status unknown. ...

@vitustang Instead of also checking the 007, would it be acceptable to just go with the date type indicator being c, d, u (and maybe t as an edge case) since we would already be checking that?

**Comment by vitustang** [comment]
@jgreben You mean instead of checking for "s" in Leader/07? The 007 field is for physical characteristics and is not used for print serials. It is used by serials in special form like electronic, microform, sound recording. So, I think you are talking about Leader/07. 

I would trust the Leader/07 = s as identifier of a serial record more than the Date type being "c", "d", or "u". The Date type code is more likely to be wrong as it is manually input (e.g. there are many "c" in records representing (erroneously) "copyright" rather than "currently published". The Leader/07 code is system-supplied when you select a "record format" when the record was first created, so it is less likely to be wrong.

**Comment by jgreben** [comment]
- Check if item is a serial using Leader/07, eighth byte of this field, e.g.
`<marc:leader>01484cas a2200361 a 4500</marc:leader>`
- If it's a serial, and if date2 is unavailable, use the current year for copyright determination, otherwise see logic in description at the top...

**Comment by peetucket** [comment]
The main description of the ticket has now been updated to reflect latest discussions.
